---
title: "Incremental value of monory"
output: md_document
---

```{r Libraries, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='hide'}

rm(list = ls())

library(data.table)
library(ggplot2)

theme_set(theme_bw(12))
```


```{r StaticParms, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='hide'}
vcLastFourSeasons = c('2013/14','2014/15','2015/16','2016/17')

dtteam_names = data.table(
   team = as.character(1:20),
   team_name = c('ARS','BOU','BHA','BUR','CHE','CRY','EVE','HUD','LEI','LIV','MCI','MUN','NEW','SOU','STK','SWA','TOT','WAT','WBA','WHU')
)
```

```{r Data, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='hide'}

load("/media/ask/9b07b759-3e7b-49b4-b47d-3a60ba5b17fd/Personal/PersonalProjects/Fantasy League/Data/2017-18/data_before01.Rdata")

dtDataset = rbindlist(
   lapply(
         seq(length(allplayers)),
         function( iPlayer ) {
            
            lPlayer = allplayers[[iPlayer]]
            lPlayerStatic = allplayersstatic$elements[[iPlayer]]

            vcDetails = unlist(lPlayerStatic[c('team_code','first_name','second_name','element_type','team')])

            if ( length(lPlayer$history_past) > 0 ) {

               rbindlist(
                  lapply(
                     lPlayer$history_past,
                     function(lPlayerHistoryPast) {

                     vcDetails = c(
                        vcDetails, 
                        unlist(lPlayerHistoryPast)
                     )

                     data.table(
                        t(vcDetails)
                     )

                  }
               )
            )

         }
            
       }
   ),
   fill = T
)

dtDataset = dtDataset[!is.na(season_name)]

dtDataset = merge(
   dtDataset,
   dtteam_names,
   'team'
)

dtPositions = rbindlist(lapply(allplayersstatic$element_types, function(x) {data.table(as.character(x$id), x$singular_name_short)}))
setnames(dtPositions, c('element_type','position'))
# dtPositions[, position := factor(x = position, levels = c('GKP','DEF','MID','FWD'))]

dtDataset = merge(
   dtDataset,
   dtPositions,
   'element_type'
)

dtDataset[, minutes := as.integer(as.character(minutes))]
dtDataset[, start_cost := as.integer(as.character(start_cost))/10]
dtDataset[, total_points := as.integer(as.character(total_points))]
dtDataset[, total_points_per_app := total_points / 38]

dtRegularsDataset = dtDataset[season_name %in% vcLastFourSeasons][minutes > (90 * 19)]
rm(dtDataset)

```


```{r OverallSensitivityTrend, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='hide', fig.height=8, fig.width=12}

# Incremental value of the pound
if ( F ) {

   ggplot(dtRegularsDataset, aes(x = start_cost, y = total_points, color = position)) + 
      geom_smooth(method = 'lm', alpha = 0) +
      # geom_jitter() +
      geom_text(aes(label = second_name), position = 'jitter') +
      facet_grid(season_name~position) +
      geom_blank()


   ggplot(dtRegularsDataset, aes(x = start_cost, y = total_points, color = position)) + 
      geom_smooth(method = 'lm', alpha = 0) +
      # geom_jitter() +
      geom_blank() +
      facet_wrap(~season_name) +
      geom_blank()
      
}

if ( F) {
      
   ggplot(dtRegularsDataset, aes(x = start_cost, y = total_points, color = position)) + 
      geom_smooth(method = 'lm', alpha = 0) +
      # geom_jitter() +
      geom_blank() +
      facet_wrap(~season_name) +
      labs(
         caption = paste0("Author: TheComeOnMan
         Data: premierleague.com")
      )
   
}
```



```{r OverallSensitivity, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='hide', fig.height=8, fig.width=12}

dtSensitivity = rbindlist(lapply(
   dtRegularsDataset[, unique(position)],
   function( cposition ) {

      rbindlist(lapply(
         dtRegularsDataset[, unique(season_name)],
         function ( cseason_name ) {

            data.table(t(c(
               cseason_name,
               cposition,
               lm(
                  total_points~start_cost,
                  dtRegularsDataset[season_name == cseason_name & position == cposition]
               )$coefficients,
               dtRegularsDataset[season_name == cseason_name & position == cposition, cor(total_points,start_cost)]
            )))

         }
      ))
      
   }
))

setnames(
   dtSensitivity,
   c('season_name','position','intercept','slope','rsquare')
)

dtSensitivity[, intercept := as.numeric(intercept)]
dtSensitivity[, slope := as.numeric(slope)]
dtSensitivity[, rsquare := as.numeric(rsquare)]

if ( F ) {
   
   ggplot(dtSensitivity) + 
      # geom_point(aes(x = position, y = slope)) +
      geom_text(aes(x = position, y = slope, label = paste(season_name, '(r2 =', round(rsquare, 2), ')'))) +
      scale_colour_continuous(low = 'white', high = 'black', space = c(0,1)) +
      labs(
         title = 'Correlation of PPM with price',
         caption = paste0("Author: TheComeOnMan
         Data: premierleague.com")
      )
}
```


```{r SensitivityCorrection, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='hide', fig.height=8, fig.width=12}

dtSensitivity = rbindlist(lapply(
   dtRegularsDataset[, unique(position)],
   function( cposition ) {

      rbindlist(lapply(
         dtRegularsDataset[, unique(season_name)],
         function ( cseason_name ) {

            data.table(t(c(
               cseason_name,
               cposition,
               lm(
                  total_points~start_cost,
                  dtRegularsDataset[!(season_name == '2015/16' & team_name %in% c('CHE','LEI'))][season_name == cseason_name & position == cposition]
               )$coefficients,
               dtRegularsDataset[!(season_name == '2015/16' & team_name %in% c('CHE','LEI'))][season_name == cseason_name & position == cposition, cor(total_points,start_cost)]
            )))

         }
      ))
      
   }
))

setnames(
   dtSensitivity,
   c('season_name','position','intercept','slope','rsquare')
)

dtSensitivity[, intercept := as.numeric(intercept)]
dtSensitivity[, slope := as.numeric(slope)]
dtSensitivity[, rsquare := as.numeric(rsquare)]

ggplot(dtSensitivity) + 
   # geom_point(aes(x = position, y = slope)) +
   geom_text(aes(x = position, y = slope, label = paste(season_name, '(r2 =', round(rsquare, 2), ')'))) +
   scale_colour_continuous(low = 'white', high = 'black', space = c(0,1)) +
   labs(
      title = 'Correlation of PPM with price (w/o CHE and LEI from 15/16)',
      caption = paste0("Author: TheComeOnMan
      Data: premierleague.com")
   )

```


```{r KeeperSensitivity, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='hide', fig.height=8, fig.width=12}

ggplot() + 
   geom_abline(data = dtSensitivity, aes(slope = slope, intercept = intercept, color = position)) +
   # geom_text(data = dtRegularsDataset, aes(x = start_cost, y = total_points, label = second_name), position = 'jitter') +
   # facet_grid(position~season_name) +
   xlim(4,14) +
   ylim(0,300) +
   facet_wrap(~season_name) +
   labs(
      # title = 'Keepers: Correlation of PPM with price',
      caption = paste0("Author: TheComeOnMan
      Data: premierleague.com")
   )


```


```{r PlayerTypeSensitivity, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, results='hide', fig.height=8, fig.width=12}

ggplot() + 
   geom_abline(data = dtSensitivity[position == 'GKP'], aes(slope = slope, intercept = intercept)) +
   geom_text(data = dtRegularsDataset[position == 'GKP'], aes(x = start_cost, y = total_points, label = second_name), position = 'jitter') +
   facet_wrap(~season_name)

ggplot() + 
   geom_abline(data = dtSensitivity[position == 'DEF'], aes(slope = slope, intercept = intercept)) +
   geom_text(data = dtRegularsDataset[position == 'DEF'], aes(x = start_cost, y = total_points, label = second_name), position = 'jitter') +
   facet_wrap(~season_name)

ggplot() + 
   geom_abline(data = dtSensitivity[position == 'MID'], aes(slope = slope, intercept = intercept)) +
   geom_text(data = dtRegularsDataset[position == 'MID'], aes(x = start_cost, y = total_points, label = second_name), position = 'jitter') +
   facet_wrap(~season_name)

ggplot() + 
   geom_abline(data = dtSensitivity[position == 'FWD'], aes(slope = slope, intercept = intercept)) +
   geom_text(data = dtRegularsDataset[position == 'FWD'], aes(x = start_cost, y = total_points, label = second_name), position = 'jitter') +
   facet_wrap(~season_name)


```